name: Github Action Example
on:
  push:
    branches: master

  pull_request:
    branches: master
    
jobs:
  ubuntu:
    name: linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: cargo build --release --verbose
